swagger: "3.0"
info:
  version: "1.0.0"
  title: "G11n Neural Machine Translation API"
  contact:
    email: "lifengd@vmware.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/nmt"
tags:
- name: "NMT"
  description: "Enable you to perform training and translation capabilities on our\
    \ local NMT setup."
- name: "Authorization"
  description: ""
schemes:
- "https"
- "http"
paths:
  /getSupportLanguagePairs:
    get:
      tags:
      - "NMT"
      summary: "Returns supported training language pairs."
      description: ""
      operationId: "get_support_language_pairs"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              type: "string"
        400:
          description: "Invalid status value"
      x-swagger-router-controller: "swagger_server.controllers.nmt_controller"
  /upload:
    post:
      tags:
      - "NMT"
      summary: "Uploads training corpus"
      security:
        - bearerAuth: []
      description: ""
      operationId: "upload"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "src_lang"
        in: "formData"
        description: "source language to train"
        required: true
        type: "string"
        enum:
        - "en-US"
        - "zh-CN"
        - "fr-FR"
      - name: "tgt_lang"
        in: "formData"
        description: "target language to train"
        required: true
        type: "string"
        enum:
        - "zh-CN"
        - "fr-FR"
        - "en-US"
      - name: "src_file"
        in: "formData"
        description: "source language file to upload"
        required: true
        type: "file"
      - name: "tgt_file"
        in: "formData"
        description: "target language file to upload"
        required: true
        type: "file"
      responses:
        200:
          description: "Upload successful"
        500:
          description: "Upload failed"
        401:
          description: "Access token missing or invalid"
          schema:
            $ref: "#/components/responses/UnauthorizedError"
      x-swagger-router-controller: "swagger_server.controllers.nmt_controller"
  /train:
    post:
      tags:
      - "NMT"
      summary: "Starts a training with corpus uploaded"
      description: ""
      operationId: "train"
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - name: "src_lang"
        in: "formData"
        description: "source language to translate"
        required: true
        type: "string"
        enum:
        - "en-US"
        - "zh-CN"
        - "fr-FR"
      - name: "tgt_lang"
        in: "formData"
        description: "target language to translate"
        required: true
        type: "string"
        enum:
        - "zh-CN"
        - "fr-FR"
        - "en-US"
      responses:
        200:
          description: "Model training successful"
        500:
          description: "Model training failed"
      security:
        - bearerAuth: []
      x-swagger-router-controller: "swagger_server.controllers.nmt_controller"
  /translate:
    post:
      tags:
      - "NMT"
      summary: "Translates with a model trained"
      description: ""
      operationId: "translate"
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - name: "src_lang"
        in: "formData"
        description: "source language to translate"
        required: true
        type: "string"
        enum:
        - "en-US"
        - "zh-CN"
        - "fr-FR"
      - name: "tgt_lang"
        in: "formData"
        description: "target language to translate"
        required: true
        type: "string"
        enum:
        - "zh-CN"
        - "fr-FR"
        - "en-US"
      responses:
        200:
          description: "Translation successful"
        500:
          description: "Translation failed"
      security:
        - bearerAuth: []
      x-swagger-router-controller: "swagger_server.controllers.nmt_controller"
  /token:
    post:
      tags:
      - "Authorization"
      summary: "Get token for using with API"
      description: ""
      operationId: "token"
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - name: "username"
        in: "formData"
        description: "Your VMware Email adrress"
        required: true
        type: "string"
      - name: "password"
        in: "formData"
        description: "Your VMware account password"
        required: true
        type: "string"
      responses:
        200:
          description: "Token generated successfully"
        500:
          description: "Token generation failed"
      x-swagger-router-controller: "swagger_server.controllers.authorization_controller"
components:
  securitySchemes:
    bearerAuth:
      type: "http"
      scheme: "bearer"
      bearerFormat: "JWT"
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
